### ISSUE TITLE
Add tables in a separate field in the output

### ISSUE THREAD

**Issue by florosx** [adbar/trafilatura#135]
When bare_extraction() is called with `include_tables==True`, I think that it makes sense to add the text extracted from the tables in a separate field (e.g. `tables`), like it's done for `comments`.
The reasoning is that tables typically contain structured content which requires different processing than the free text contained in the rest of the article. And it would also ensure a common handling of all `include*` parameters.
(we can also do that for the extracted links as well, currently this is fairly easy to achieve because the markdown syntax for the detected urls is kept, but I think would be better to output them in a separate field separate from the text).

**Comment by adbar** [comment]
Hi @florosx, IMHO the tables are different from the comments since they are really expected to be part of the main text of a page, so by design they should appear within the output text. In addition, in most cases I know the element order is important.

If you wish to process the tables differently then you could use XML as output format to process certain elements according to your preferences. Here is an [example](https://www.oxygenxml.com/archives/xsl-list/200910/msg00071.html) where an element is moved to the end with XSLT.
If you prefer another format you could also use internal/Python output and process the elements before calling a function provided by Trafilatura for conversion.

**Comment by florosx** [comment]
Hi @adbar, sorry for the late reply. You have a good point there, in the end I agree with you.
