### ISSUE TITLE
Title persists in body content despite being correctly detected

### ISSUE THREAD

**Issue by naftalibeder** [adbar/trafilatura#160]
Sometimes the beginning of an extracted article contains the article’s title, even though the title is also extracted correctly. This is especially noticeable in New York Times articles, such as [this one](https://www.nytimes.com/2022/01/11/magazine/kidney-donation-ethics.html).

My assumption is that the title should not be considered part of the body - is that correct?

**Comment by adbar** [comment]
Hi @naftalibeder, whether titles are part of articles is a matter for discussion. If you use XML output you can delete the `<head rend="h1">` node.
What shouldn't be there is the "Send any friend a story" between title and body, that's definitely boilerplate.

**Comment by adbar** [comment]
I believe the main issue here is solved so I'm closing the thread.

**Comment by naftalibeder** [comment]
Nice, your commit fixes the boilerplate share block. Thanks!

As for titles, I would argue that it shouldn't be part of the article body, because the title can be acquired individually, so in some sense it creates unnecessary duplication. I'm not sure what the argument is for keeping the title in the body, but I'm certainly interested in hearing it. :)

**Comment by adbar** [comment]
I can understand your question since the distinction indeed isn't clear-cut.

The functional explanation would be that if the title is displayed centrally with the main text then it is part of it. Titles can be part of teaser elements (see your other issue in #164) along with one or two paragraphs. In my experience most people would say they are part of the main text even if they are rather a kind of introduction.

In any case, the title case can be solved individually according to your needs. One can easily delete a header preceded by no text. The case of teaser paragraphs is much more complex.

**Comment by naftalibeder** [comment]
That’s fair! Let me know if you’d consider a config with a default (`include_title=True`) or if you think it should just be up to the user.

**Comment by adbar** [comment]
At this point I think it should be up to the user.
