### ISSUE TITLE
Different extraction result on the same input

### ISSUE THREAD

**Issue by jkangsta** [adbar/trafilatura#17]
I tried to run the following extraction snippet on the same HTML input multiple times, but every 4th extraction returned shorter extraction.

```
link = '...'
html = scrape(link)
prev_extraction = None

for x in range(10):
    extraction = trafilatura.extract(html, include_comments=False,
        include_tables=False, no_fallback=True, target_language='en')
    if prev_extraction:
        if prev_extraction != extraction:
            print('Extraction looks weird!')
    prev_extraction = extraction
```

Is there any parameter I should be using or is this a bug to be fixed?
Thanks!

**Comment by adbar** [comment]
Hi, this happens because a deduplication algorithm is activated by default on element, paragraph and document levels. To make sure not to run it you can just pass an additional `deduplicate=False` argument to `trafilatura.extract()`.
This additional feature will ship with the next package version, until then please use the latest code from the repository: `pip install -U git+https://github.com/adbar/trafilatura.git`

**Comment by adbar** [comment]
The new version (0.5.2) is out, deduplication is now off by default.
