### ISSUE TITLE
Completely fails at thecyberwire.com

### ISSUE THREAD

**Issue by 097115** [adbar/trafilatura#171]
E.g.,

    trafilatura -u "https://thecyberwire.com/newsletters/daily-briefing/11/27"

...or

    trafilatura -u "https://thecyberwire.com/stories/d1543536fd3949f3a506c59f5e4e60b0/diplomacy-continues-as-does-preparation-for-hybrid-war"

...return just nothing :(

    ~> trafilatura --version
    Trafilatura 1.0.0 - Python 3.9.2

**Comment by adbar** [comment]
Hi @097115, I cannot reproduce the bug, it works on my computer. I see two options:
- Maybe there is a problem with the download, can you download a page separately (say as `page.html`) and then type `< page.html trafilatura` to see if you get an output?
- If you are on Apple Silicon / M1, the HTML parser may fail, which may result in no output as well. It is current being fixed by the developer.

**Comment by adbar** [comment]
Hi @097115, it means it is a problem of [user agent string](https://en.wikipedia.org/wiki/User_agent). The default one on Trafilatura may have been restricted from your website of interest (403 error code), or the default library `urllib3` somehow doesn't work.
From there I see two options:
- You install pycurl via `pip install pycurl` or `pip install trafilatura[all]` to see if it does the trick, since `curl` on the command-line works
- You change the user-agent string in the [settings file](https://trafilatura.readthedocs.io/en/latest/usage-python.html#settings-file)

**Comment by 097115** [comment]
Thanks, @adbar, adding `pycurl` works :)
