### ISSUE TITLE
Trafilatura appears to ignore <meta charset="...">

### ISSUE THREAD

**Issue by zackw** [adbar/trafilatura#231]
```
>>> fragment = '<html><head><meta charset="iso-8859-1"></head><body>the majestic mööse</body></html>'
>>> trafilatura.extract(fragment)
'the majestic mööse'
```
So far so good—the charset tag _should_ have no effect when Trafilatura is handed a Unicode string.  But look what happens if the text is supplied as a byte string, in the encoding stated by the charset tag:

```
>>> trafilatura.extract(fragment.encode('iso-8859-1'))
'the majestic m——se'
```

The ös have become em dashes.  What _seems_ to be going on is that Trafilatura is relying solely on charset_normalizer, which isn't paying any attention to the charset tag:

```
>>> charset_normalizer.detect(fragment.encode('iso-8859-1'))
{'encoding': 'hp_roman8', 'language': 'English', 'confidence': 1.0}
```

This is going to be super annoying to work around: I'm going to have to implement the HTML5 encoding detection algorithm myself.  Trafilatura should do that (you can probably crib code from https://github.com/html5lib/html5lib-python/blob/master/html5lib/_inputstream.py).

**Comment by adbar** [comment]
Hi @zackw, this is an interesting corner case but my experimence tells me that relying on `meta charset` declarations is often the wrong way to go: `charset_normalizer` is interesting precisely because it starts from the assumption that the strings to decode are going to be noisy. The chosen string is typically too short for a web page, the encoding detection will do better with more content.

Nevertheless, here is how to solve the problem:
- Please install `cchardet` manually or `trafilatura[all]`, I wrote a disambiguation loop which works best with both decoders installed. As there were problems with `cchardet` on some platforms I didn't include it in the standard requirements.

**Comment by adbar** [comment]
Hi @zackw, did the answer above solve the issue?

**Comment by aruno14** [comment]
Install `cchardet` works for me with a page using `Shift_JIS`.
