### ISSUE TITLE
Html extraction

### ISSUE THREAD

**Issue by slavaGanzin** [adbar/trafilatura#268]
Hi, Adrien, awesome library, works like a charm.
In my use case I need not a text, but an html extract. Seems like I look into an API, and issues, but I didn't find any way to get an extract of document not as plain text, but as html containing that text. Am I missing something?

**Comment by slavaGanzin** [comment]
What was I expecting is get this result usign `extract(downloaded, output_format='html')`. But it just return text, and as I know understand it should raise an exception :)

BTW, it's very confusing that `extract(downloaded, output_format='json')`
return a string. Yes I know that I can use bare_extraction, but unexpected.

Overall thanks for your work, I could make a PR. If this will be approved.

**Comment by adbar** [comment]
Hi @slavaGanzin, thanks for your feedback!

- You could definitely write a PR to raise an exception for unknown output formats.
- HTML as output won't be possible as is because the content is converted to XML internally. However, you could use XML as output format and work on the nodes as you'd do with HTML.
- The output has to be a string sooner or later because there are people using the package on the command-line. I didn't think of actually using something else than a string for consistency reasons, maybe that's something we could tackle later.

**Comment by slavaGanzin** [comment]
Thanks Adrien
