### ISSUE TITLE
Feature request: keeping links

### ISSUE THREAD

**Issue by posobin** [adbar/trafilatura#38]
I can't find a way to extract text while preserving the `<a href>` tags in it (probably replacing those tags with `link` tags, output type would be xml). Would be great to have it. If I were to help add it, where should I look?

**Comment by adbar** [comment]
Hi, you're right, the links currently end up being discarded.

Some links are kept in order to check for link density before being stripped, so it happens
- here: https://github.com/adbar/trafilatura/blob/master/trafilatura/htmlprocessing.py#L156
- and here: https://github.com/adbar/trafilatura/blob/master/trafilatura/core.py#L335

Basically we are talking about
1. an argument in `convert_tags` (in `htmlprocessing.py`, conversion from `a` to `link`) and `extract_content` (in `core.py`) to keep them
2. subsequent adaptations in the rest of the code, you can have a look at the newly added `include_images` #35 

Feel free to draft a pull request if you're interested.

**Comment by adbar** [comment]
Hi @posobin, I decided to add such an option in 681dd9853674de6ea4ea8cd24c8d6f83fc56624d. It's not perfect yet but should cover most links.

**Comment by posobin** [comment]
Hi Adrien! Great news, thank you! I'll check it out in a few weeks. I have been working on an unrelated part of the project for the past month so didn't have a chance to add it myself.
