### ISSUE TITLE
Change of license? GPLv3+ → Apache 2.0

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#512]
Dear all,

Trafilatura is now widely used and it has become apparent that the GPL license is not prevalent in Python packages, its potential implications are also not easily understood. To better align with community standards and promote ongoing development, I plan to transition Trafilatura's software license to Apache 2.0.

As you have contributed lines still currently in use it would be best to get your agreement in order to move forward on this. For the sake of simplicity I use the list provided by Github and you may be mentioned below even if your contributions focus on documentation or evaluation files.

For reference, other packages of mine concerned by similar changes:
- https://github.com/adbar/courlan/issues/80
- https://github.com/adbar/htmldate/issues/131

If you agree please add a corresponding message to this thread. If not please contact me or open a public discussion.

- @felipehertzer: :heavy_check_mark:
- @vbarbaresi: :heavy_check_mark:
- @knit-bee: :heavy_check_mark:
- @LukasBBAW: _pending_
- @phongtnit: _pending_
- @andremacola: :heavy_check_mark:
- @idoshamun: :heavy_check_mark:
- @edkrueger: _pending_
- @EllieLockhart: _pending_
- @tonyyanga: :heavy_check_mark:
- @immortal-autumn: _pending_
- @glacierck: _pending_
- @deedy5: :heavy_check_mark:
- @k-sareen: _pending_
- @dsgibbons: :heavy_check_mark:
- @mrienstra: :heavy_check_mark:
- @LaundroMat: :heavy_check_mark:
- @sdondley: _pending_
- @Korben00: _pending_
- @awwitecki: :heavy_check_mark:
- @feltcat: :heavy_check_mark:
- @muellermartin: :heavy_check_mark:
- @marksmayo: :heavy_check_mark:
- @sashkab: _pending_
- @HeLehm: :heavy_check_mark:
- @tomwojcik: :heavy_check_mark:
- @Yomguithereal: :heavy_check_mark:
- @Ashikpaul: :heavy_check_mark:
- @Maddesea: :heavy_check_mark:
- @jaesivsm: :heavy_check_mark:
- @dmoklaf: :heavy_check_mark:

**Comment by tomwojcik** [comment]
I agree.

**Comment by HeLehm** [comment]
I agree.

**Comment by idoshamun** [comment]
I agree

**Comment by dmoklaf** [comment]
Hello Adrien,

of course this looks great.

And thanks again for your outstanding work ! I use Trafilatura with great pleasure every day.

Regards,

Raphael Geronimi
+33777947835

**Comment by Yomguithereal** [comment]
My tool is GPLv3. I don't really know if this is compatible with apache 2.0, the subject seems complicated, but I personally don't really care and don't have an issue with you migrating to apache 2.0.

**Comment by awwitecki** [comment]
I agree

**Comment by deedy5** [comment]
I don't mind

**Comment by muellermartin** [comment]
I agree

**Comment by andremacola** [comment]
I agree

**Comment by adbar** [comment]
@Yomguithereal You can certainly include a package under an OSI-approved license in a package under GPL. The other way round is unclear and the answer can depend on who you're asking and which software community you're in (e.g. in R the GPL is much more common).
See the discussion in the datatrove issue above if you're interested.

**Comment by tonyyanga** [comment]
I agre.

**Comment by sashkab** [comment]
I agree.

**Comment by marksmayo** [comment]
Agree

**Comment by feltcat** [comment]
No objections from me (same as earlier).

**Comment by mrienstra** [comment]
Fine by me!

**Comment by felipehertzer** [comment]
I agree.

**Comment by k-sareen** [comment]
I agree.

**Comment by LaundroMat** [comment]
I agree

**Comment by vbarbaresi** [comment]
I agree

**Comment by dsgibbons** [comment]
I agree

**Comment by Maddesea** [comment]
Agreed
________________________________
From: Adrien Barbaresi ***@***.***>
Sent: Wednesday, February 21, 2024 8:10:35 AM
To: adbar/trafilatura ***@***.***>
Cc: Madden, Sean A ***@***.***>; Mention ***@***.***>
Subject: [adbar/trafilatura] Change of license? GPLv3+ → Apache 2.0 (Issue #512)


[This email originated from outside of OSU. Use caution with links and attachments.]

Dear all,

Trafilatura is now widely used and it has become apparent that the GPL license is not prevalent in Python packages, its potential implications are also not easily understood. To better align with community standards and promote ongoing development, I plan to transition Trafilatura's software license to Apache 2.0.

As you have contributed lines still currently in use it would be best to get your agreement in order to move forward on this. For the sake of simplicity I use the list provided by Github and you may be mentioned below even if your contributions focus on documentation or evaluation files.

For reference, other packages of mine concerned by similar changes:

  *   adbar/courlan#80<https://github.com/adbar/courlan/issues/80>
  *   adbar/htmldate#131<https://github.com/adbar/htmldate/issues/131>

If you agree please add a corresponding message to this thread. If not please contact me or open a public discussion.

  *   @felipehertzer<https://github.com/felipehertzer>: pending
  *   @vbarbaresi<https://github.com/vbarbaresi>: pending
  *   @knit-bee<https://github.com/knit-bee>: pending
  *   @LukasBBAW<https://github.com/LukasBBAW>: pending
  *   @phongtnit<https://github.com/phongtnit>: pending
  *   @andremacola<https://github.com/andremacola>: pending
  *   @idoshamun<https://github.com/idoshamun>: pending
  *   @edkrueger<https://github.com/edkrueger>: pending
  *   @EllieLockhart<https://github.com/EllieLockhart>: pending
  *   @tonyyanga<https://github.com/tonyyanga>: pending
  *   @immortal-autumn<https://github.com/immortal-autumn>: pending
  *   @glacierck<https://github.com/glacierck>: pending
  *   @deedy5<https://github.com/deedy5>: pending
  *   @k-sareen<https://github.com/k-sareen>: pending
  *   @dsgibbons<https://github.com/dsgibbons>: pending
  *   @mrienstra<https://github.com/mrienstra>: pending
  *   @LaundroMat<https://github.com/LaundroMat>: pending
  *   @sdondley<https://github.com/sdondley>: pending
  *   @Korben00<https://github.com/Korben00>: pending
  *   @awwitecki<https://github.com/awwitecki>: pending
  *   @feltcat<https://github.com/feltcat>: pending
  *   @muellermartin<https://github.com/muellermartin>: pending
  *   @marksmayo<https://github.com/marksmayo>: pending
  *   @sashkab<https://github.com/sashkab>: pending
  *   @HeLehm<https://github.com/HeLehm>: pending
  *   @tomwojcik<https://github.com/tomwojcik>: pending
  *   @Yomguithereal<https://github.com/Yomguithereal>: pending
  *   @Ashikpaul<https://github.com/Ashikpaul>: pending
  *   @Maddesea<https://github.com/Maddesea>: pending
  *   @jaesivsm<https://github.com/jaesivsm>: pending
  *   @dmoklaf<https://github.com/dmoklaf>: pending

**Comment by adbar** [comment]
For the record: I waited about a month, all answers are in favor, I'm moving forward with the change.
