### ISSUE TITLE
Extraction with `include_images=True` takes too much time

### ISSUE THREAD

**Issue by Honesty-of-the-Cavernous-Tissue** [adbar/trafilatura#651]
`python`: `3.12.0`
`trafilatura`: `1.11.0`

```
url = 'https://www.gencergaming.com/lg-24mp60g-24-1ms-full-hd-freesync-oyuncu-monitoru'

import trafilatura

s = timeit.default_timer()
resp = trafilatura.fetch_url(url)
print(timeit.default_timer() - s)

s = timeit.default_timer()
content = trafilatura.extract(resp, favor_precision=True, deduplicate=True)
print(timeit.default_timer() - s)

# content = trafilatura.extract(resp, favor_precision=True, include_images=True, deduplicate=True)


```

normally it takes few time
but after i add `include_images=True`, time consue become extremely unacceptable to over 10 mins

![image](https://github.com/user-attachments/assets/39e8f4f7-438f-4403-b0e0-8b3fee5174dd)

it seems happens here: https://github.com/adbar/trafilatura/blob/30c34a5239ca53fca268fd7b85413bbfa50f8301/trafilatura/main_extractor.py#L429

i wonder if this check nessessary for image extraction and  is there something i can do to skip over this behavior meanwhile not closing images extraction behavior

big thanks!

**Comment by adbar** [comment]
Hi @Honesty-of-the-Cavernous-Tissue, thanks for reporting and investigating the bug. Images are not my priority so I don't test it extensively. The function `is_image_file` is just a regex that takes too long here because there is too much text in a img link.

As a side note, there are buggy web pages from time to time and there was a timeout for cases like this but it's only active on the CLI because using `signal` proved detrimental to the versatility of the package (use in complex multiprocessing systems).

Here the easiest solution would be to limit the size of text fed to `is_image_file` to a reasonable value.

**Comment by Honesty-of-the-Cavernous-Tissue** [comment]
@adbar Thanks for reply:

I've tried tried your suggestion to limit the size of text length lessthan `2048`, and i work's well
``` 
def handle_image(element):
    "Process image elements and their relevant attributes."
    processed_element = Element(element.tag)

    for attr in ("data-src", "src"):
        src = element.get(attr)
        if src is not None and len(src) > 2048:
           continue
        if is_image_file(src):
            processed_element.set("src", src)
            break
    else:
        # take the first corresponding attribute
        for attr, value in element.attrib.items():
            if attr.startswith("data-src") and is_image_file(value):
                processed_element.set("src", value)
                break
```

**Comment by adbar** [comment]
Thanks for your input, I prefer to use the length threshold directly in the function `is_image_file()`.
