### ISSUE TITLE
Date processing returns None in some cases

### ISSUE THREAD

**Issue by saminahbab** [adbar/trafilatura#75]
for this url: "https://www.thecanary.co/feature/2021/05/19/another-by-election-headache-is-incoming-for-keir-starmer", if I use 
`downloaded = trafilatura.fetch_url(url)
trafilatura.bare_extraction(downloaded)
`

I get a json with the text and this is a good result. However, if I use 
`trafilatura.bare_extraction(downloaded, with_metadata=True)`

The result is None.

I believe this is not correct behaviour potentially, and that the method should not fail like this.

Thank you, however, for this library, it really is quite good!

**Comment by adbar** [comment]
Hi @saminahbab, thanks for your feedback, there is indeed a bug in URL extraction for the page you mentioned.
Since no URL can be extracted, the `with_metadata` argument results in the document being discarded.

For a quick fix please enter a valid URL (since you have one for the download) as follows:

```
download_url = "https://www.thecanary.co/feature/2021/05/19/another-by-election-headache-is-incoming-for-keir-starmer"
trafilatura.bare_extraction(downloaded, with_metadata=True, url=download_url)
```

**Comment by adbar** [comment]
In the mean time this bug has been solved.
